jwt:
    secret: ENC[AES256_GCM,data:DEpoTmPR8wbJcupl,iv:Vxc6ujIO2JA6Uu2X8Lfm9UObowq2EscnZ/pDxPw1+g0=,tag:nI2HHqYVRNvd8dG0joTtcQ==,type:str]
spring:
    data:
        mongodb:
            uri: ENC[AES256_GCM,data:Wvqs59+LAJgGg+cBxuhQlSXAXPEoOUiD/mniPsrvhpfs2PI+uk7eIW9dMOmzBy+Y5s83Bvn2Z0EwhTLmQDy2ChfDxysef5B2xJ/Ld9j06aPq36h6O9jDmIcvI9GxD3PscJ0/Qg==,iv:lqDxTbMddoM64VupBF/nsZPCe8YHlwZGKHd7TZGFcQg=,tag:Hu5GBwXTlevJTQ759qZBZw==,type:str]
            database: ENC[AES256_GCM,data:9XOv2CCYClQ=,iv:qA2KOi/n+AhNB5kMguxlucyr0ZdKJQZBQJlZCtBb7nc=,tag:Jjhyn3CSaQdGXOF+AUkIGg==,type:str]
server:
    port: ENC[AES256_GCM,data:3pc=,iv:WnZiBCc3jW/xfSvOf8YAjGKivxjg4GLatp9gSCCv5Is=,tag:7AXEKx9xEKGlboumQM+y0A==,type:int]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14rfhef89myvcwtngnep3tuc2hq0cukgkgn3w98teaa8sqhttd9pqslq2gr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3aVRyRUhJZkdzeldMSGJC
            WE9tak5kWHB0U05qeFU2bHI2M0pJYW9Nb2k4CjNvSmdQTnBiMmJ0SjF6U21qZzRq
            L3YrZmVNc1FxcExsb1JjNHhoR0tWQVEKLS0tIHlZQzZXRHF0TzFOK1F4NUh5UVdm
            Q0tVR0dZYU8wV1pXa3FTdW5ycUthancKY7c5Dbz9FUfmOsMbTRVGKb3BEA55XGX5
            iB4LIV/gPtN6+zcegBh9N6Rocz2/EUfClna4B3bhXsrvegugjVXRdg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1dh8a2ar5vtue8upyxdk9n47uqqpgmkrnst0cr623qszqm9tptv5sx9026c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2eUUreEtQVjI1NWxFRjlO
            WHNmaldOVTZybGlueFVuTjIvNURNS1RlcEdvCmFoN2U2MitJSjFyMW40bUN4enpI
            dUZON1VVaGRsV2E4NlcveEhkSWFlblEKLS0tIEQ4ekMyS2tDbERUSUJvZGVVMTBw
            MWs0WkVBQ2JmRWdPbjFSdFRpVVdWL0UKwLPzKrs7wijkecM/OnqUh0ERDEOQ/pxJ
            GqcT1NIeUP/oaap1QIiDuRHXSztBZujXmHdIA0qfb8yE155i3/ekMw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1cq6xtpmyzsum0fc2uk2dwda6rksp6dd8v2m654ev604d4n65cu8synu99s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzbFdJdzY2WEtaeDZ1akQx
            aGQ1Z0Vuc1ArZ2NVQXB5cjFVVFlBOTNURlM0Ci9nbnR2RUw3b2lOK1RORTVybVRG
            WUpPSjh0UXdzSnIyTXRqYVBMT00wamsKLS0tIGpTbmN2RFdGY21YL2taaDE4YnVY
            emdiSTF0a3IyaE5NRDBCbHptODA4dncKiHZq5IWPRI9elrvaNCWiUOeyCyzPvdoN
            o5WHUmGKYSd37EsVUs6RWw+3mCQGIaSlxB9nKR5OUOCyxDJwW+xAKw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-08T05:12:23Z"
    mac: ENC[AES256_GCM,data:kJZK1Z+7lGzLS68Bo7KeySDg8et5BPSwK/B/PQ9/l8ltsL/4Da6n/hU3gg/r0dJHG9Qr9p2oBd4rb7x0VQzBJLaqcPRhxUMwtmju9NAlq12RuaOZbGE0KBTwQ1lgwzhOE+byLDFJnQ/GsW6yN54Z/golZuZ0kHL85ZiNV9zdNiI=,iv:UvU5DOZpxyH77/xnoQhefEW2nAyOI13+v2+6RnbMjN4=,tag:pJ7jV9yGRTMjpVe/pU5LmQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
